import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const mode = process.argv[2] === "upload" ? "upload" : "deploy";
const isWindows = process.platform === "win32";
const wranglerConfig = ".wrangler/deploy-wrangler.jsonc";
const workerEntry = ".open-next/worker.js";

run("node", ["scripts/prepare-cloudflare-deploy.mjs"]);
runBin("opennextjs-cloudflare", ["build", "--config", wranglerConfig]);
assertWorkerEntry();
runBin("opennextjs-cloudflare", [mode, "--config", wranglerConfig]);

function run(command, args) {
	console.log(`\n> ${[command, ...args].join(" ")}`);
	execFileSync(command, args, {
		cwd: root,
		env: process.env,
		stdio: "inherit",
	});
}

function runBin(command, args) {
	const bin = path.join(root, "node_modules", ".bin", isWindows ? `${command}.cmd` : command);
	run(bin, args);
}

function assertWorkerEntry() {
	const absoluteEntry = path.join(root, workerEntry);
	if (existsSync(absoluteEntry)) {
		const size = statSync(absoluteEntry).size;
		console.log(`\nVerified ${workerEntry} (${size} bytes).`);
		return;
	}

	const openNextFiles = listFiles(path.join(root, ".open-next"));
	throw new Error(`${workerEntry} was not generated by the OpenNext build. Found under .open-next:\n${openNextFiles || "(nothing)"}`);
}

function listFiles(directory) {
	if (!existsSync(directory)) {
		return "";
	}

	const files = [];
	walk(directory, files);
	return files.sort().join("\n");
}

function walk(directory, files) {
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const absolutePath = path.join(directory, entry.name);
		if (entry.isDirectory()) {
			walk(absolutePath, files);
			continue;
		}

		if (entry.isFile()) {
			files.push(path.relative(root, absolutePath));
		}
	}
}
